# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096f96b4e52591ac2ac8888ca81af31dac1d853587fd7d7f499e685788f5c7fa35da29b3e99962eb492f3bfce76fb6098c3b42d6e82b91699c4407edddea8907

test:
  secret_key_base: d0d0e78b406fc81a0372070651848e4763da31a28e037a96dbd807c9960adea939106ef050c6675f011302862d1d239680f70830f46485d4b7a060e8f720cccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
